#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

# Do this because moksha expects its config file in either /etc/ or in the cwd.
cd $OPENSHIFT_REPO_DIR/diy/

# Actually start it and redirect logs
nohup $OPENSHIFT_REPO_DIR/data/venv/bin/paster serve \
    --pid-file=$OPENSHIFT_HOMEDIR/diy-0.1/run/paster.pid \
    --log-file=$OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log \
    development.ini \
    start \
    openshift_internal_ip=$OPENSHIFT_INTERNAL_IP
